host: 0.0.0.0
port: 8091
callback_poll_seconds: 1
plugin:
    fronius:
      poll_seconds: 1
      history_ticks: 10000
      publish_ticks: -1
      push_upstream: True
    netatmo:
      poll_seconds: 300
      history_ticks: 150
      publish_ticks: -1
      push_upstream: True
    davis:
      poll_seconds: -1
      history_ticks: 10000
      publish_ticks: -1
      push_upstream: True
    wunderground:
      poll_seconds: 900
      history_ticks: 10
      publish_ticks: -1
      push_upstream: True
