host: 0.0.0.0
port: 8091
callback_poll_seconds: 1
plugin:
    fronius:
      poll_seconds: 1
      buffer_ticks: 60
      history_days: 5
      history_ticks: 1250000
      publish_ticks: -1
      push_upstream: True
    davis:
      poll_seconds: -1
      buffer_ticks: 30
      history_days: 5
      history_ticks: 201000
      publish_ticks: -1
      push_upstream: True
    netatmo:
      poll_seconds: 50
      buffer_ticks: 10
      history_days: 5
      history_ticks: 335000
      publish_ticks: -1
      push_upstream: True
    wunderground:
      poll_seconds: 300
      buffer_ticks: 10
      history_days: 5
      history_ticks: 5000
      publish_ticks: -1
      push_upstream: True
