host: 0.0.0.0
port: 8091
publish_host: 37.187.106.16
publish_port: 1883
publish_topic: asystem/anode/datum
publish_seconds: 3613
save_on_exit: True
save_seconds: 86400
plugin:
    fronius:
      poll_seconds: 1
      buffer_ticks: 60
      history_partitions: 14
      history_ticks: 5000000
      history_partition_seconds: 86400
      repeat_seconds: 101
      publish_ticks: -1
      publish_upstream: True
    davis:
      poll_seconds: -1
      buffer_ticks: 30
      history_partitions: 14
      history_ticks: 900000
      history_partition_seconds: 86400
      repeat_seconds: 103
      publish_ticks: -1
      publish_upstream: True
    netatmo:
      poll_seconds: 50
      buffer_ticks: 10
      history_partitions: 14
      history_ticks: 400000
      history_partition_seconds: 86400
      repeat_seconds: 107
      publish_ticks: -1
      publish_upstream: True
    wunderground:
      poll_seconds: 300
      buffer_ticks: 5
      history_partitions: 14
      history_ticks: 800000
      history_partition_seconds: 86400
      repeat_seconds: 111
      publish_ticks: -1
      publish_upstream: True
