name: ${project.artifactId}
channels:
- defaults
dependencies:
- dill=0.2.7
- boto=2.46.1
- scipy=0.19.0
- pandas=0.20.1
- scikit-learn=0.18.1
- seaborn=0.7.1
- pyspark=2.2.0
- pip=9.0.1
- python=2.7.11
